--- #YAML:1.0
name:               Net-DNS-CloudFlare-DDNS
version:            0.03
abstract:           Object orientated Dynamic DNS interface
author:
    - Peter Roberts <me+dev@peter-r.co.uk>
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Carp:            1.2
    JSON::Any:       1.28
    LWP::UserAgent:  6.05
    Moo:             1.003
    perl:            

    Readonly:        1.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
