---
abstract: 'Object Orientated Dynamic DNS Interface to CloudFlare DNS'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  File::Spec: '3.40'
  Test::Exception: '0.32'
  Try::Tiny: '0.11'
  perl: '5.014'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-DNS-CloudFlare-DDNS
provides:
  Net::DNS::CloudFlare::DDNS:
    file: lib/Net/DNS/CloudFlare/DDNS.pm
    version: 0.06_3
  Net::DNS::CloudFlare::DDNS::Types:
    file: lib/Net/DNS/CloudFlare/DDNS/Types.pm
    version: 0.06_3
requires:
  Carp: '1.26'
  CloudFlare::Client: '0'
  IPC::System::Simple: '1.22'
  List::Util: '1.24'
  Modern::Perl: '1.20120105'
  Moose: '1.22'
  MooseX::StrictConstructor: '0.13'
  Readonly: '1.04'
  TryCatch: '1.003001'
  Type::Tiny: 0.039_12
  autodie: '2.11'
  indirect: '0.24'
  namespace::autoclean: '0.12'
  perl: '5.014'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-DNS-CloudFlare-DDNS
  homepage: https://bitbucket.org/pwr22/net-dns-cloudflare-ddns
  repository: git://git@bitbucket.org:pwr22/net-dns-cloudflare-ddns.git
version: 0.06_3
